apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-varseltekst-monitor
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-varseltekst-monitor-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "1"
      memory: 800Mi
    requests:
      cpu: "10m"
      memory: 50Mi
  gcp:
    sqlInstances:
      - name: varseltekster
        type: POSTGRES_14
        tier: db-f1-micro
        diskType: SSD
        highAvailability: false
        diskSize: 50
        diskAutoresize: false
        autoBackupHour: 3
        databases:
          - name: varseltekster
            envVarPrefix: DB
        maintenance:
          day: 1
          hour: 4
        cascadingDelete: false
  kafka:
    pool: nav-prod
