apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-varseltekst-monitor
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - "https://tms-varseltekst-monitor.ansatt.nav.no"
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: '77cce29b-3cb8-45f7-8014-a551fb93f8a6'
      tenant: nav.no
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /metrics
  secureLogs:
    enabled: true
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 800Mi
    requests:
      cpu: "10m"
      memory: 50Mi
  gcp:
    sqlInstances:
      - name: varseltekster
        type: POSTGRES_14
        tier: db-custom-1-3840
        diskType: SSD
        highAvailability: false
        diskSize: 50
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: varseltekster
            envVarPrefix: DB
        maintenance:
          day: 1
          hour: 4
        cascadingDelete: false
  kafka:
    pool: nav-prod
  env:
    - name: KAFKA_GROUP_ID
      value: "varseltekst-monitor-06"
    - name: KAFKA_RESET_POLICY
      value: "earliest"
    - name: VARSEL_TOPIC
      value: "min-side.brukervarsel-v1"
