create view totalt_antall_per_sms_tekst_inkl_std as select * from (select * from totalt_antall_per_sms_tekst union all select count(*) as antall, '<standardtekst>' as tekst from varsel where varsel.sms_preferert and varsel.sms_tekst is null group by tekst) as inkl_std order by antall desc;
create view totalt_antall_per_epost_tittel_inkl_std as select * from (select * from totalt_antall_per_epost_tittel union all select count(*) as antall, '<standardtekst>' as tekst from varsel where varsel.epost_preferert and varsel.epost_tittel is null group by tekst) as inkl_std order by antall desc;
create view totalt_antall_per_epost_tekst_inkl_std as select * from (select * from totalt_antall_per_epost_tekst union all select count(*) as antall, '<standardtekst>' as tekst from varsel where varsel.epost_preferert and varsel.epost_tekst is null group by tekst) as inkl_std order by antall desc;

create view antall_per_sms_tekst_inkl_std as select * from (select * from antall_per_sms_tekst union all select count(*) as antall, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), '<standardtekst>' as tekst from varsel where varsel.sms_preferert and varsel.sms_tekst is null group by varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), tekst) as inkl_std order by antall desc;
create view antall_per_epost_tittel_inkl_std as select * from (select * from antall_per_epost_tittel union all select count(*) as antall, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), '<standardtekst>' as tekst from varsel where varsel.epost_preferert and varsel.epost_tittel is null group by varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), tekst) as inkl_std order by antall desc;
create view antall_per_epost_tekst_inkl_std as select * from (select * from antall_per_epost_tekst union all select count(*) as antall, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), '<standardtekst>' as tekst from varsel where varsel.epost_preferert and varsel.epost_tekst is null group by varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), tekst) as inkl_std order by antall desc;

create view totalt_antall_per_sms_tekst_inkl_std_siste_30_dager_inkl_std as select * from (select * from totalt_antall_per_sms_tekst_siste_30_dager union all select count(*) as antall, '<standardtekst>' as tekst from varsel where tidspunkt > (now()::date - interval '30 day') and varsel.sms_preferert and varsel.sms_tekst is null group by tekst) as inkl_std order by antall desc;
create view totalt_antall_per_epost_tittel_inkl_std_siste_30_dager_inkl_std as select * from (select * from totalt_antall_per_epost_tittel_siste_30_dager union all select count(*) as antall, '<standardtekst>' as tekst from varsel where tidspunkt > (now()::date - interval '30 day') and varsel.epost_preferert and varsel.epost_tittel is null group by tekst) as inkl_std order by antall desc;
create view totalt_antall_per_epost_tekst_inkl_std_siste_30_dager_inkl_std as select * from (select * from totalt_antall_per_epost_tekst_siste_30_dager union all select count(*) as antall, '<standardtekst>' as tekst from varsel where tidspunkt > (now()::date - interval '30 day') and varsel.epost_preferert and varsel.epost_tekst is null group by tekst) as inkl_std order by antall desc;

create view antall_per_sms_tekst_inkl_std_siste_30_dager_inkl_std as select * from (select * from antall_per_sms_tekst_siste_30_dager union all select count(*) as antall, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), '<standardtekst>' as tekst from varsel where tidspunkt > (now()::date - interval '30 day') and varsel.sms_preferert and varsel.sms_tekst is null group by varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), tekst) as inkl_std order by antall desc;
create view antall_per_epost_tittel_inkl_std_siste_30_dager_inkl_std as select * from (select * from antall_per_epost_tittel_siste_30_dager union all select count(*) as antall, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), '<standardtekst>' as tekst from varsel where tidspunkt > (now()::date - interval '30 day') and varsel.epost_preferert and varsel.epost_tittel is null group by varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), tekst) as inkl_std order by antall desc;
create view antall_per_epost_tekst_inkl_std_siste_30_dager_inkl_std as select * from (select * from antall_per_epost_tekst_siste_30_dager union all select count(*) as antall, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), '<standardtekst>' as tekst from varsel where tidspunkt > (now()::date - interval '30 day') and varsel.epost_preferert and varsel.epost_tekst is null group by varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), tekst) as inkl_std order by antall desc;

create view totalt_antall_per_sms_tekst_inkl_std_siste_90_dager_inkl_std as select * from (select * from totalt_antall_per_sms_tekst_siste_90_dager union all select count(*) as antall, '<standardtekst>' as tekst from varsel where tidspunkt > (now()::date - interval '90 day') and varsel.sms_preferert and varsel.sms_tekst is null group by tekst) as inkl_std order by antall desc;
create view totalt_antall_per_epost_tittel_inkl_std_siste_90_dager_inkl_std as select * from (select * from totalt_antall_per_epost_tittel_siste_90_dager union all select count(*) as antall, '<standardtekst>' as tekst from varsel where tidspunkt > (now()::date - interval '90 day') and varsel.epost_preferert and varsel.epost_tittel is null group by tekst) as inkl_std order by antall desc;
create view totalt_antall_per_epost_tekst_inkl_std_siste_90_dager_inkl_std as select * from (select * from totalt_antall_per_epost_tekst_siste_90_dager union all select count(*) as antall, '<standardtekst>' as tekst from varsel where tidspunkt > (now()::date - interval '90 day') and varsel.epost_preferert and varsel.epost_tekst is null group by tekst) as inkl_std order by antall desc;

create view antall_per_sms_tekst_inkl_std_siste_90_dager_inkl_std as select * from (select * from antall_per_sms_tekst_siste_90_dager union all select count(*) as antall, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), '<standardtekst>' as tekst from varsel where tidspunkt > (now()::date - interval '90 day') and varsel.sms_preferert and varsel.sms_tekst is null group by varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), tekst) as inkl_std order by antall desc;
create view antall_per_epost_tittel_inkl_std_siste_90_dager_inkl_std as select * from (select * from antall_per_epost_tittel_siste_90_dager union all select count(*) as antall, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), '<standardtekst>' as tekst from varsel where tidspunkt > (now()::date - interval '90 day') and varsel.epost_preferert and varsel.epost_tittel is null group by varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), tekst) as inkl_std order by antall desc;
create view antall_per_epost_tekst_inkl_std_siste_90_dager_inkl_std as select * from (select * from antall_per_epost_tekst_siste_90_dager union all select count(*) as antall, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), '<standardtekst>' as tekst from varsel where tidspunkt > (now()::date - interval '90 day') and varsel.epost_preferert and varsel.epost_tekst is null group by varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), tekst) as inkl_std order by antall desc;
