create view totalt_antall_per_web_tekst as select count(*) as antall, wt.tekst from varsel join web_tekst wt on varsel.web_tekst = wt.id group by wt.tekst order by antall desc;
create view totalt_antall_per_sms_tekst as select count(*) as antall, st.tekst from varsel join sms_tekst st on varsel.sms_tekst = st.id group by st.tekst order by antall desc;
create view totalt_antall_per_epost_tittel as select count(*) as antall, eti.tekst from varsel join epost_tittel eti on varsel.epost_tittel = eti.id group by eti.tekst order by antall desc;
create view totalt_antall_per_epost_tekst as select count(*) as antall, ete.tekst from varsel join epost_tekst ete on varsel.epost_tekst = ete.id group by ete.tekst order by antall desc;

create view antall_per_web_tekst as select count(*) as antall, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), wt.tekst from varsel join web_tekst wt on varsel.web_tekst = wt.id group by wt.tekst, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), wt.tekst order by antall desc;
create view antall_per_sms_tekst as select count(*) as antall, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), st.tekst from varsel join sms_tekst st on varsel.sms_tekst = st.id group by st.tekst, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), st.tekst order by antall desc;
create view antall_per_epost_tittel as select count(*) as antall, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), eti.tekst from varsel join epost_tittel eti on varsel.epost_tittel = eti.id group by eti.tekst, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), eti.tekst order by antall desc;
create view antall_per_epost_tekst as select count(*) as antall, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), ete.tekst from varsel join epost_tekst ete on varsel.epost_tekst = ete.id group by ete.tekst, varsel.event_type, concat(varsel.produsent_namespace, ':', varsel.produsent_appnavn), ete.tekst order by antall desc;
