apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-varseltekst-monitor
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "1"
      memory: 800Mi
    requests:
      cpu: "10m"
      memory: 50Mi
  gcp:
    sqlInstances:
      - name: varseltekster
        type: POSTGRES_14
        tier: db-f1-micro
        diskType: SSD
        highAvailability: false
        diskSize: 10
        diskAutoresize: false
        autoBackupHour: 3
        databases:
          - name: varseltekster
            envVarPrefix: DB
        maintenance:
          day: 1
          hour: 4
        cascadingDelete: false
  ingresses:
    - "https://tms-varseltekst-monitor.ansatt.dev.nav.no"
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: "cbe637e2-317f-48e1-a951-ce52fcea3fae"
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  kafka:
    pool: nav-dev
  env:
    - name: KAFKA_GROUP_ID
      value: "varseltekst-monitor-test-03"
    - name: KAFKA_RESET_POLICY
      value: "earliest"
    - name: VARSEL_TOPIC
      value: "min-side.brukervarsel-v1"
