name: Deploy revision

on:
  repository_dispatch:
    types: deploy-revision

env:
  COMMIT_SHA: ${{ github.event.client_payload.commit }}

permissions:
  packages: write

jobs:
  build:
    name: Bygg prosjekt og push docker-image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Sjekk ut commit
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Sett opp java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Bygg prosjekt
        run: ./gradlew assemble

      - name: Build og push docker-image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: min-side
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy:
    name: Deploy til NAIS
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        cluster: ${{ github.event.client_payload.clusters }}
    steps:
      - name: Sjekk ut commit
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: 'Deploy til ${{ inputs.cluster }}'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ matrix.CLUSTER }}
          RESOURCE: ./nais/${{ matrix.CLUSTER }}/nais.yaml
          VAR: version=${{ needs.build.outputs.image }}
