name: Bygg og publiser docker-image for main

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/**
      - README.md
      - howto.md

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Sjekk ut prosjekt
        uses: actions/checkout@v4

      - name: Sett opp java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Bygg prosjekt og kjør tester
        run: ./gradlew build

      - name: Build og push docker-image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: min-side
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy:
    name: Deploy til NAIS
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        cluster: [dev-gcp, prod-gcp]
    steps:
      - name: Sjekk ut prosjekt
        uses: actions/checkout@v4

      - name: 'Sjekk om deploy til ${{ matrix.cluster }} er mulig'
        run: echo "DEPLOY_CONFIG_DEFINED=$([[ -f ./nais/${{ matrix.cluster }}/nais.yaml ]] && echo 'true' || echo 'false')" >> $GITHUB_ENV

      - name: 'Deploy til ${{ matrix.cluster }}'
        if: env.DEPLOY_CONFIG_DEFINED == 'true'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: ./nais/${{ matrix.cluster }}/nais.yaml
          VAR: version=${{ needs.build.outputs.image }}
